version: "3.8"

services:
  herridez-backend:
    build: .
    container_name: herridez-backend
    restart: always
    network_mode: "host"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3001
