/**
 * Seeds users + one primary bike per user from `data/` JSON (HerRidez app docs).
 *
 * Sources (generated by scripts):
 *   scripts/extract-user-md.cjs   → src/seeds/data/userProfiles.json
 *   scripts/extract-userbike-md.cjs → src/seeds/data/bikeCatalog.json
 *
 * Phones: 9610000001 … (does not overlap default dummy rider 9800… range).
 *
 * Run:
 *   npm run seed:data-users-bikes
 *   SEED_PHONE_START=9610000001 npm run seed:data-users-bikes
 */

import { readFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import mongoose from "mongoose";
import connectDB from "../config/db.js";
import logger from "../config/logger.js";
import User from "../models/user.model.js";
import Bike from "../models/bike.model.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

type UserProfile = {
  name: string;
  age: number;
  city: string;
  state: string;
  country: string;
  ridingLevel: "Beginner" | "Intermediate" | "Advanced" | "Expert";
  ridingStyle: string[];
  yearsOfExperience: number;
};

type BikeRow = { brand: string; model: string; cc: number };

const ALLOWED_STYLES = new Set([
  "Track",
  "Touring",
  "Street",
  "Commute",
  "Racing",
]);

/** Map dataset labels → User model enum */
function mapRidingStyles(styles: string[]): string[] {
  const map: Record<string, string> = {
    Sport: "Racing",
    City: "Commute",
    Adventure: "Touring",
    Cruiser: "Street",
  };
  const out: string[] = [];
  for (const s of styles) {
    const m = map[s] ?? (ALLOWED_STYLES.has(s) ? s : "Commute");
    if (!out.includes(m)) out.push(m);
  }
  return out.length ? out : ["Commute"];
}

function cityCoords(city: string): { lat: number; lng: number; name: string } {
  const c = city.toLowerCase();
  if (c.includes("delhi")) return { lat: 28.6139, lng: 77.209, name: "Delhi" };
  if (c.includes("bangalore") || c.includes("bengaluru"))
    return { lat: 12.9716, lng: 77.5946, name: "Bangalore" };
  return { lat: 19.076, lng: 72.8777, name: "Mumbai" };
}

function regPlateFor(city: string, seq: number): string {
  const c = city.toLowerCase();
  let st = "MH";
  if (c.includes("delhi")) st = "DL";
  else if (c.includes("bangalore") || c.includes("bengaluru")) st = "KA";
  const n2 = String(10 + (seq % 80)).padStart(2, "0");
  const n4 = String(1000 + (seq % 9000)).padStart(4, "0");
  return `${st}${n2}AB${n4}`;
}

const COLORS = [
  "Black",
  "Pearl White",
  "Racing Blue",
  "Metallic Grey",
  "Candy Red",
  "Matte Black",
];

/** Curated superbike / motorcycle stock URLs (Unsplash — see bikeimage/README.md). */
export const SEED_BIKE_IMAGE_URLS: string[] = JSON.parse(
  readFileSync(path.join(__dirname, "data/superbikeImageUrls.json"), "utf8"),
) as string[];

function handleFromName(name: string, index: number): string {
  const base = name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "")
    .slice(0, 12);
  const suffix = String(100 + index).slice(-3);
  let h = `${base || "rider"}${suffix}`;
  if (h.length > 20) h = h.slice(0, 20);
  if (h.length < 3) h = `r${String(index).padStart(2, "0")}`;
  return h;
}

async function seedDataUsersAndBikes() {
  await connectDB();

  const profilesPath = path.join(__dirname, "data/userProfiles.json");
  const bikesPath = path.join(__dirname, "data/bikeCatalog.json");

  const profiles = JSON.parse(
    readFileSync(profilesPath, "utf8"),
  ) as UserProfile[];
  const catalog = JSON.parse(readFileSync(bikesPath, "utf8")) as BikeRow[];

  const phoneStart = parseInt(
    process.env.SEED_PHONE_START || "9610000001",
    10,
  );

  let createdUsers = 0;
  let createdBikes = 0;
  let skippedExisting = 0;

  const session = await mongoose.startSession();
  session.startTransaction();

  try {
    for (let i = 0; i < profiles.length; i++) {
      const p = profiles[i];
      const phone = String(phoneStart + i);
      if (!/^[0-9]{10}$/.test(phone)) {
        logger.error(`Skip invalid phone derivation: ${phone}`);
        continue;
      }

      const exists = await User.findOne({ phone }).select("_id").session(session).lean();
      if (exists) {
        skippedExisting++;
        continue;
      }

      const loc = cityCoords(p.city);
      const email = `seed.${phone}@herridez.local`;
      const handle = handleFromName(p.name, i);

      const user = await User.create(
        [
          {
            phone,
            email,
            handle,
            name: p.name,
            country: p.country || "India",
            state: p.state,
            city: p.city,
            verified: true,
            verificationStatus: "approved",
            ridingLevel: p.ridingLevel,
            ridingStyle: mapRidingStyles(p.ridingStyle || []),
            yearsOfExperience: Math.max(
              0,
              Math.min(50, p.yearsOfExperience ?? 0),
            ),
            currentLocation: {
              lat: loc.lat + (Math.random() - 0.5) * 0.04,
              lng: loc.lng + (Math.random() - 0.5) * 0.04,
              name: loc.name,
            },
            onboardingCompleted: true,
            onboardingStep: 100,
            bio: `${p.name} · ${p.ridingLevel} rider in ${p.city}.`,
          },
        ],
        { session },
      );
      const u = user[0];
      createdUsers++;

      const bikeTemplate = catalog[i % catalog.length];
      const bikeYear =
        new Date().getFullYear() - (i % 4 === 3 ? 0 : (i % 3) + 1);

      const bike = await Bike.create(
        [
          {
            userId: u._id,
            brand: bikeTemplate.brand,
            model: bikeTemplate.model,
            year: bikeYear,
            cc: bikeTemplate.cc,
            color: COLORS[i % COLORS.length],
            registrationNumber: regPlateFor(p.city, i),
            primary: true,
            mileage: Math.floor(500 + Math.random() * 12000),
            imageUrl: SEED_BIKE_IMAGE_URLS[i % SEED_BIKE_IMAGE_URLS.length],
            notes: `${bikeTemplate.brand} ${bikeTemplate.model} — seeded ride.`,
            status: "active",
          },
        ],
        { session },
      );

      await User.findByIdAndUpdate(
        u._id,
        { $push: { bikes: bike[0]._id } },
        { session },
      );
      createdBikes++;
    }

    await session.commitTransaction();
  } catch (e: unknown) {
    await session.abortTransaction();
    const msg = e instanceof Error ? e.message : String(e);
    logger.error(`❌ Seed failed: ${msg}`);
    throw e;
  } finally {
    session.endSession();
  }

  logger.info(
    `✅ dataUsersAndBikes: users=${createdUsers}, bikes=${createdBikes}, skipped(existing phone)=${skippedExisting}`,
  );
}

const runAsScript = process.argv[1]?.includes("dataUsersAndBikes.seed");
if (runAsScript) {
  seedDataUsersAndBikes()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}

export default seedDataUsersAndBikes;
